# Generated by Django 4.0.3 on 2022-03-31 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationhistory',
            name='account_number_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_task.score'),
        ),
    ]
