# Generated by Django 4.0.3 on 2022-03-31 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0003_rename_account_number_sender_translationhistory_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translationhistory',
            old_name='score',
            new_name='account_number_sender',
        ),
    ]
