# Generated by Django 4.0.3 on 2022-03-31 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0004_rename_score_translationhistory_account_number_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translationhistory',
            old_name='account_number_recipient',
            new_name='score_recipient',
        ),
        migrations.RenameField(
            model_name='translationhistory',
            old_name='account_number_sender',
            new_name='score_sender',
        ),
    ]
