# Generated by Django 4.0.3 on 2022-04-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0005_rename_account_number_recipient_translationhistory_score_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='account_number',
            field=models.CharField(max_length=16, verbose_name='Номер счета'),
        ),
    ]
